language: node_js
script:
- npm run precommit
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: lPWcCXHl+KgyWKSaDUZLKaQDVyzPoKM4UHS4ETUdYtsroJB3nKbyQSkGu/lZHjCZLcBPLtwvcj87CJ/dkxm/O7xqD63HdQ5CCbAOcmFwjaRIptBIoruoi0wA3vIpdGHTheCmAsgliwLQMn/qZlT5gNfKKXsQB02iqt/gtvymRbpBsaxHgbVrgNv9shubCAXZnM5xMAiJq2c6Nof5BWAZcDDF8J8oC3tiKV0LXSwSDmM5o/jNEu9AJEZsjIqcOmeIFoF9g4zun6/XY43QworxHmWo3MXbOERFZ8pHxslstgbyrxaEAvW63PAESjJ5rRwlFoIj7YkyOMTsDW1pBG6+CV/4KtEzEZQfkE2py1zFffeUZaM9oVxTpTNtpvdEFFX/34cjYEPbDmQ+e0D6dDrHwRm5Mz/K9ucu6LrilbRVr9kFs4fPvWwQ4lW17A5FsxwEI/f3ij9st7qeoXYJ1J7bzbgQv9Ew8isX5Rzq5UfkBYRu7vv4WrBFSzxX5hZ0sWj+NL+X0K639lfpQQnto4rGZinGztcBUNX4Y/L06lwjHvDR690qDtxArCC0I6Ol/ZNaE6kmbXixWioJYa9QZ4r+IOCRM9rHxxXqEustZ9s3bsjHcG6Jfaey5hArUdiowBl0yA5kkctp/WeHTfQfrDSgKQ3/Z8Z7Nuowkf0OY2iiG74=
  app: twlevelup-syd-2017-s2-purple
  on:
    repo: twlevelup/SydBuild2017S2_Purple
notifications:
  slack:
    secure: zsZz+J15ZtDlub0/ardMTzcBlqQc+qtoaDKbWJh72jSFxQD4uux0G9VOnwHK+gFL3JNhxNgHuauM5rygzLJuudtUz/B6yf7mnZodkv1qDcciCS1AOjIHFR04olURohOxm/dLx7UtwadSZ9vivtnAnAqfIJPr9eVsnthDoVQsLfbZgc/93ZelzPzlgNVRACILVCKkPO6UVMgyF3OzXbyfHTRD0hxUiY/ghSeV1g7cH3UiHYUd17Vc/FWiBSuaWC0R9bzl+IepidRLMQuR1+iZgHfW60aH0QU7a6PkLZyjCcOpg1k+gMAcoBsmNULuW5KHJR5jPdbyOT83Yaei7xusdObSmTf9SX/EX9vrcT/lIjDxIqNyj/tdfl7cJfdiStQkUE520BCZ3nuHGjlm2rG5r3IEO89vVUpsrzV0uWVIxixlgO7lOYvOXMyMAX78tqUd2NtdgqLkmu40BTyeHPaRaJbJ8BLZq1xscsv5hoHgY680+dGQyUI9G+yWR/eo9kM+HafeTEY9Tz85XAm0WMeJDT1YIut+nAKBBF1Chj397YEPWYLZyFo75wcj43W4k32ypALvLWrP+Pw7bJgnU5YYdLYy7v+y0SXurGnO8grkGwPmQDOZiBb8WBCtkvhf1orCYEC39agjV7jyZVjMTcBq2ew2t1Rf3Zs93XA4slDn8pg=
